-- =======================================================
-- SUPABASE POSTGRESQL SCHEMA: QUẢN LÝ QUỸ
-- Dán toàn bộ mã này vào: Supabase Dashboard -> SQL Editor -> Run
-- =======================================================

-- 1. XÓA BẢNG CŨ (NẾU CÓ)
DROP TABLE IF EXISTS fund_contributions CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS members CASCADE;

-- 2. BẢNG THÀNH VIÊN
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT DEFAULT '',
    bank_id TEXT DEFAULT 'MBBank',
    bank_account_no TEXT DEFAULT '',
    bank_account_name TEXT DEFAULT '',
    avatar_url TEXT DEFAULT '',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. BẢNG CÀI ĐẶT HỆ THỐNG
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 4. BẢNG THEO DÕI ĐÓNG QUỸ THEO TUẦN (4 TUẦN / THÁNG)
CREATE TABLE fund_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    year INT NOT NULL,
    month INT NOT NULL,
    week INT NOT NULL,
    amount NUMERIC(15,2) DEFAULT 10000,
    is_paid INT DEFAULT 0,
    paid_at TIMESTAMP WITH TIME ZONE NULL,
    note TEXT NULL,
    CONSTRAINT uq_member_week UNIQUE (member_id, year, month, week)
);

-- 5. BẢNG GIAO DỊCH THU / CHI
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    amount NUMERIC(15,2) NOT NULL,
    category TEXT NOT NULL,
    member_id BIGINT NULL,
    member_name TEXT NULL,
    description TEXT NULL,
    receipt_url TEXT NULL,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TẮT RLS HOẶC CHO PHÉP PUBLIC TRUY CẬP (ANON KEY)
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE fund_contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read/Write Members" ON members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Settings" ON settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Fund Contributions" ON fund_contributions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);

-- 7. NẠP DỮ LIỆU CẤU HÌNH MẪU SẠCH
INSERT INTO settings (key, value) VALUES 
('admin_pin', '888888'),
('group_password', '123456'),
('bank_id', 'MBBank'),
('bank_account_no', ''),
('bank_account_name', 'THU QUY'),
('weekly_amount', '10000'),
('monthly_amount', '40000'),
('qr_template', 'compact2'),
('custom_qr_url', '');

-- 8. NẠP 10 THÀNH VIÊN MẪU
INSERT INTO members (id, name, phone, bank_id, bank_account_no, bank_account_name) VALUES 
(1, 'Thành viên 1', '', 'MBBank', '', ''),
(2, 'Thành viên 2', '', 'Vietcombank', '', ''),
(3, 'Thành viên 3', '', 'Techcombank', '', ''),
(4, 'Thành viên 4', '', 'ACB', '', ''),
(5, 'Thành viên 5', '', 'BIDV', '', ''),
(6, 'Thành viên 6', '', 'TPBank', '', ''),
(7, 'Thành viên 7', '', 'VPBank', '', ''),
(8, 'Thành viên 8', '', 'VietinBank', '', ''),
(9, 'Thành viên 9', '', 'MBBank', '', ''),
(10, 'Thành viên 10', '', 'Sacombank', '', '');
